### ISSUE TITLE
Feedback from twitter

### ISSUE THREAD

**Issue by AngelMunoz** [AngelMunoz/Mondocks#1]
I took a few notes from Twitter earlier today 

- [x] look a way to create [indexes ](https://docs.mongodb.com/manual/reference/command/createIndexes/#dbcmd.createIndexes)
- [x] remove prefixes from custom operations
- [x] pass the collection name as the parameter of the CE's
- [x] return typed results from the command execution
- [x] add BSON decoders
- [x]  add method helpers to create things like filters, fields, matching criteria

**Comment by AngelMunoz** [comment]
all of these have their own issue now, so I will close this

**Comment by Alkasai** [comment]
I like the new typed results!
What do you think about wrapping this into some sort of function that just returns seq of type User, instead of coursor?

``` fsharp
let result = db.RunCommand<FindResult<User>>(JsonCommand over20)
printfn $"FindResult Ok: %f{result.ok}"
result.cursor.firstBatch |> Seq.iter (fun value -> printfn $"%A{value}")
```

**Comment by AngelMunoz** [comment]
@Alkasai we can review any kind of helper function as part of #12
