### ISSUE TITLE
Example of using array filters

### ISSUE THREAD

**Issue by ArchitectCat** [AngelMunoz/Mondocks#25]
Hello!

Can someone show an example of using array filters in queries?
Looks like currently they are represented as just "object" type, so its not clear on how to actually utilize them.

Thank you!

**Comment by AngelMunoz** [comment]
Hello there, I haven't used `arrayFilters` before normally I don't deal with that kind of data but we follow the MongoDB Command Spec
if you check the [updates section](https://docs.mongodb.com/manual/reference/command/update/index.html#update-statements) a little bit bellow is a specific part for `arrayFilters`, in mongo they look like this 
```js
// Example 1
[
  { $or: [{"x.a": {$gt: 85}}, {"x.b": {$gt: 80}}] }
]
// Example 2
[
  { $and: [{"x.a": {$gt: 85}}, {"x.b": {$gt: 80}}] }
]
// Example 3
[
  { "x.a": { $gt: 85 }, "x.b": { $gt: 80 } }
]
```
in F# they would look basically the same
```fsharp
// Example 1
[
  {| ``$or`` = [ {| ``x.a`` = {| ``$gt`` = 85 |} |}, {| ``x.b`` = {| ``$gt`` = 80 |} | }] |}
]
// Example 2
[
  {| ``$and`` = [ {| ``x.a`` = {| ``$gt`` = 85 |} |}, {| ``x.b`` = {| `$gt` = 80 |} |}] |}
]
// Example 3
[
  {| ``x.a`` = {| ``$gt`` = 85 |},``x.b`` = {| ``$gt`` = 80 |} |}
]
```

If we go to the [update guide](https://docs.mongodb.com/manual/reference/command/update/index.html#update-command-arrayfilters) we can see other examples as well
```js
db.runCommand({
   update: "students2",
   updates: [
     { q: { },
       u: { $set: { "grades.$[elem].mean" : 100 } },
       arrayFilters: [ { "elem.grade": { $gte: 85 } } ], 
       multi: true  }
   ]
})
```
that would roughly be equivalent to 
```fsharp
// array-filters.fsx
#r "nuget: Mondocks"

open Mondocks.Queries

let updateCmd =
    update "students2" {
        updates [ 
            {| q = {|  |}
               u = {| ``$set`` = {| ``grades.$[elem].mean`` = 100 |} |}
               arrayFilters = [ {| ``elem.grade`` = {| ``$gte`` = 85 |} |} ]
               /// notice `|> box` here
               multi = true |} |> box 
       ]
    }

printfn $"%A{updateCmd}"
(* pretty printed
{
  "update":"students2",
  "updates":[
      { "q":{ },
        "u":{ "$set":{ "grades.$[elem].mean":{ "$numberInt":"100" } } },
        "arrayFilters":[ { "elem.grade":{ "$gte":{ "$numberInt":"85" } } } ],
        "multi":true } 
  ]
} *)
(* raw output
"{"update":"students2","updates":[{"arrayFilters":[{"elem.grade":{"$gte":{"$numberInt":"85"}}}],"multi":true,"q":{},"u":{"$set":{"grades.$[elem].mean":{"$numberInt":"100"}}}}]}"
*)
```
> ***Note***: You can copy/paste that into dotnet fsi or in a F# script

the take away here would be if you know how to do it in mongo, the easiest way to do it in Mondocks is by translating basically 1-1 via anonymous records and boxing them where an `obj seq` or `obj list` is required

If you have a couple of samples that you can share with us I can gladly guide you where to put them if you feel like contributing, if you feel it's too much you can share the samples here and I'll update the docs when I'm available to do so. In any case, I'll try to document this usage when I have a chance

please let me know if this helps you, or if this example (from mongo docs) is kind of confusing we can try to come up with a simpler example

**Comment by AngelMunoz** [comment]
I'll close this issue for the moment, feel free to re-open if necessary

**Comment by ArchitectCat** [comment]
The examples helped, thank you!
