### ISSUE TITLE
Query for a subset of the document

### ISSUE THREAD

**Issue by toburger** [AngelMunoz/Mondocks#26]
It should be possible to define a document only partially and the query should still work.
At the moment I have to define every JSON field or else I get a FormatException.

#### Document

```json
{
  "_id": "foo",
  "Active": true,
  "LicenseInfo": {
    ...
  },
  ...
}
```

#### Query

```fsharp
type Poi =
  { _id: string
    Active: bool }

let q = find "pois" { ... }
db.RunCommandAsync<FindResult<Poi>>(JsonCommand q)
```

```
System.FormatException: An error occurred while deserializing the cursor property of class Mondocks.Types.FindResult`1[[FSI_0063+Poi, FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]: An error occurred while deserializing the firstBatch property of class Mondocks.Types.Cursor`1[[FSI_0063+Poi, FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]: Element 'LicenseInfo' does not match any field or property of class FSI_0063+Poi. ---> System.FormatException: An error occurred while deserializing the firstBatch property of class Mondocks.Types.Cursor`1[[FSI_0063+Poi, FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]: Element 'LicenseInfo' does not match any field or property of class FSI_0063+Poi. ---> System.FormatException: Element 'LicenseInfo' does not match any field or property of class FSI_0063+Poi.
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
```

Especially in a production environment, where the document schema can grow independently from your application code this ends up in runtime errors that can easily avoided by allowing to map to a subset of the document.

**Comment by AngelMunoz** [comment]
Hey there, thanks for reporting this, ~to be honest, this is still something that's puzzling my head since the returning JSON document can be wildly different depending on the actual database info, the `FindResult` it's just a convenience type that I added but for more control, you can use the `BsonDocument`. That being said did you try to use a projection for this? e.g.~

Rephrasing all of that, I think the projections are meant for this use case, I'm not sure if you tried them, an example would be the following:

```fsharp
#r "nuget: Mondocks"
#r "nuget: MongoDB.Driver"

open MongoDB.Driver
open MongoDB.Bson
open Mondocks.Types
open Mondocks.Queries

let q = 
    find "pois" {
        projection {| Active = 1 |}
   }

let db = MongoClient("mongodb://localhost:27017").GetDatabase("samples");
let result = db.RunCommand<FindResult<{| _id: ObjectId; Active: bool |}>>(JsonCommand q)
printfn "%A" q
printfn "%A" result.cursor.firstBatch
```
running that in dotnet fsi with a collection with documents like these
```json
{
	"_id" : ObjectId("5fe370bb4149f55a6cacc255"),
	"Name" : "yay",
	"Active" : true,
	"ExtraProp" : 213
}
```
gives you the following result
```
[Loading C:\Users\daniel\AppData\Local\Temp\nuget\25240--bb771246-28bc-4390-b0ce-c8c13813ac69\Project.fsproj.fsx]
namespace FSI_0006.Project

"{"find":"pois","projection":{"Active":{"$numberInt":"1"}}}"

seq
  [{ Active = true
     _id = 5fe370bb4149f55a6cacc250 }; { Active = true
                                         _id = 5fe370bb4149f55a6cacc251 };
   { Active = true
     _id = 5fe370bb4149f55a6cacc252 }; { Active = true
                                         _id = 5fe370bb4149f55a6cacc253 }; ...]

val q : string = "{"find":"pois","projection":{"Active":{"$numberInt":"1"}}}"
val db : IMongoDatabase
val result : FindResult<{| Active: bool; _id: ObjectId |}> =
  { cursor = { firstBatch = <seq>
               ns = "samples.pois" }
    ok = 1.0 }
val it : unit = ()

>
```

by the way `{| Active: bool; _id: ObjectId |}` can be replaced by your own *subset type*
if you need to [project values in a nested object](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/#return-specific-fields-in-embedded-documents) you need to do something like this
```fsharp
find "embedded_docs" {
  projection {| Active: 1; Name = 0;  ``property.innerProperty`` = 1 |}
}
```
which would return you a document like this
```json
{
   "Active": true,
   "property": { "innerProperty": "some value" }
}
```
the generic type you pass to `FindResult<'T>` would need to have that shape or use a matching anonymous object.

If this is not what you actually wanted please let me know to see how can this be addressed

**Comment by toburger** [comment]
Good hint about the projection! This definitely solves the runtime error.

However I do strongly believe that **omitting properties should be resilient and not throw an exception**.
If your app isn't the only client you will sooner or later encounter runtime errors because the schema has grown over the time.

_You don't want to be in the situation where your app crashes because of such an exception and having to add the property to your types, then recompile and redeploy your application, even though the new property has absolutely no value for you app. I was there, thanks you [WCF Data Services](https://docs.microsoft.com/en-us/dotnet/api/system.data.services.client.dataservicecontext.ignoremissingproperties?view=netframework-4.8)!_

**I absolutely love the thin abstraction of the library** and knowing that I could write my own `FindPartialResult` is good to know but I think a better solution would be to have `FindResult` be resilient and eventually have a `FindExactResult` that throws an exception if the schema doesn't match the type.

**Comment by toburger** [comment]
After playing with the low level MongoDB driver I realized that this behavior comes from the underlying lib.

You need to annotate your type(s) with `BsonIgnoreExtraElements` so it ignores the missing properties.

```fsharp
[<BsonIgnoreExtraElements>]
type Poi =
    { _id: string
      Active: bool }
```

Solves it for me!

**Comment by AngelMunoz** [comment]
Ah I see, yes that comes from the driver itself, there's also a catch all property
In case you need it, it can be a bson document or a `Dictionary<string, obj>`
```fsharp
[<BsonExtraElements>]
ExtraElements: BsonDocument
```
I have annotated some of the convenience types with the ignore one precisely because of what you way have faced already

**Comment by AngelMunoz** [comment]
> I think a better solution would be to have FindResult be resilient and eventually have a FindExactResult that throws an exception if the schema doesn't match the type.

I like this idea, although this would have to be on an `Extensions` package since this lib as it is doesn't take a dependency on the driver, just the bson library I'll explore that once I have a chance

In the meantime, I'll close this, feel free to re-open if necessary

**Comment by toburger** [comment]
I'm absolutely fine with closing the issue! 👍 

The behavior comes from the underlying library and can be resolved by applying the `BsonIgnoreExtraElements` or `BsonExtraElements` (thanks) attributes or defining a global convention.
Sorry, I should have been experimenting and understanding more before opening an issue.

Still a bit buzzled that this is the default behavior of the .NET driver for MonogDB.
